backend:
  name: github
  repo: NicodemusN/Alhosite
  branch: master
  base_url: https://NicodemusN.github.io
  auth_endpoint: /Alhosite/admin/oauth.html

media_folder: "static/uploads"
public_folder: "/uploads"

local_backend: true

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
