name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo including theme
      - name: Checkout repository
        uses: actions/checkout@v4
        #with:
        #  submodules: recursive  # safe even if theme isn’t a submodule

      # Step 2: Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.125.6"
          extended: true

      # Step 3: Build the site
      - name: Build
        run: hugo --minify

      # Step 4: Upload the public folder as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
